apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
  namespace: raspi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: device
  name: device-service
  namespace: raspi
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: device
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: plc
  name: plc-service
  namespace: raspi
spec:
  ports:
  - port: 502
    protocol: TCP
    targetPort: 502
  selector:
    app: plc
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt-service
  namespace: raspi
spec:
  selector:
    app: mqtt
  type: NodePort
  ports:
  - port: 1883
    targetPort: 1883